services:
  db:
    image: mysql:8.0
    container_name: laravel_db
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-proot" ]
      interval: 5s
      timeout: 3s
      retries: 30

  app:
    image: laravel-ci-image:latest
    container_name: laravel_app

    volumes:
      - jenkins-laravel_jenkins_home:/var/jenkins_home

    working_dir: /var/jenkins_home/workspace/laravel-ci

    ports:
      - "8000:8000"

    depends_on:
      db:
        condition: service_healthy

    environment:
      APP_ENV: testing
      APP_DEBUG: "true"
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: dockerYmg
      DB_USERNAME: root
      DB_PASSWORD: ServBay.dev

    command: >
      sh -lc "
        set -e
        cd /var/jenkins_home/workspace/laravel-ci

        cp -n .env.example .env || true
        php artisan key:generate --force || true
        php artisan config:clear || true

        echo '⏳ DB bağlantısı bekleniyor...'
        until php -r '
          $$h=getenv(\"DB_HOST\");
          $$d=getenv(\"DB_DATABASE\");
          $$u=getenv(\"DB_USERNAME\");
          $$p=getenv(\"DB_PASSWORD\");
          try { new PDO(\"mysql:host=$$h;dbname=$$d\", $$u, $$p); exit(0); }
          catch(Exception $$e) { exit(1); }
        '; do sleep 2; done

        php artisan migrate:fresh --force
        php artisan serve --host=0.0.0.0 --port=8000
      "

volumes:
  jenkins-laravel_jenkins_home:
    external: true
